# sensor model: dyp_a05/w200d
sensor_model: "dyp_a05"
device_path: "/dev/serial/by-id/usb-u-blox_AG_-_www.u-blox.com_u-blox_GNSS_receiver-if00" # Path to receiver port
baud_rate: 115200 # baud rate
frame_id: "ultrasonic_link"
topic_name: "ultrasonic"
